
apiVersion: v1
kind: Namespace
metadata:
  name: sre-techtask
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
  namespace: sre-techtask
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: yesinteractive/dadjokes
        ports:
        - containerPort: 8100
---          
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
  namespace: sre-techtask
spec:
  selector:
    app: myapp
  ports:
   -  port: 80
      targetPort: 8100
  type: LoadBalancer

---    
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-app-ingress
  namespace: sre-techtask
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/validate: "true"
spec:
  rules:
    - host: myapp.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: my-app-service
                port:
                  number: 80
